export { default as Campus } from "./Campus.jpeg";
export { default as cardBG } from "./cardBG.jpg";
export { default as contactUs } from "./contactUs.jpg";
export { default as FormImage } from "./FormImage.png";
export { default as hero } from "./hero.jpeg";
export { default as homeInHand } from "./homeInHand.jpg";
export { default as logo } from "./logo.png";
export { default as meritBasedScholarship } from "./meritBasedScholarship.jpg";
export { default as scholarshipBanner } from "./scholarshipBanner.jpg";
export { default as stipend } from "./stipend.jpg";
export { default as studentFreeShip } from "./studentFreeShip.jpg";
export { default as Testimonials01 } from "./Testimonials 01.svg";
export { default as Testimonials02 } from "./Testimonials 02.svg";
export { default as Testimonials03 } from "./Testimonials 03.svg";
export { default as whyUsBanner } from "./whyUsBanner.jpg";
export { default as magnifyingGlassQuestionMarkIcon } from "./Icons/magnifyingGlassQuestionMarkIcon.png";
export { default as meritBasedScholarshipIcon } from "./Icons/meritBasedScholarshipIcon.png";
export { default as stipendIcon } from "./Icons/stipendIcon.png";
export { default as studentFreeShipIcon } from "./Icons/studentFreeShipIcon.png";
export { default as principle } from "./Principle.png";
export { default as university } from "./University.png";
export { default as OurCourses } from "./OurCourses.jpg";
export { default as BlogImage } from "./BlogImage.jpg";
